In [1]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [2]:
dataset = pd.read_csv("Placement.csv")

In [3]:
dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [4]:
dataset.info()  # dataset.info() shows the detailed information and properties of the dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sl_no           215 non-null    int64
 1   gender          215 non-null    object
 2   ssc_p           215 non-null    float64
 3   ssc_b           215 non-null    object
 4   hsc_p           215 non-null    float64
 5   hsc_b           215 non-null    object
 6   hsc_s           215 non-null    object
 7   degree_p        215 non-null    float64
 8   degree_t        215 non-null    object
 9   workex          215 non-null    object
 10  etest_p         215 non-null    float64
 11  specialisation  215 non-null    object
 12  mba_p           215 non-null    float64
 13  status          215 non-null    object
 14  salary          148 non-null    float64
dtypes: float64(6), int64(1), object(8)
memory usage: 25.3+ KB

In [5]:
#EXPECTED OUTPUT
#Quan = ["ssc_p ","hsc_p","degree_p"," etest_p","mba_p","salary"] # CONTINOUS VALUE
#Qual = ["gender","ssc_b","hsc_b","hsc_s","degree_t","workex","specialisation","status"] # NOMINAL VALUE

In [6]:
# dir(dataset)    # dir(dataset) Used to view all attributes/methods that allows to perform specific operation

In [7]:
dataset.columns   # View all the column names of dataset.

Index(['sl_no', 'gender', 'ssc_p', 'ssc_b', 'hsc_p', 'hsc_b', 'hsc_s',
       'degree_p', 'degree_t', 'workex', 'etest_p', 'specialisation', 'mba_p',
       'status', 'salary'],
      dtype='object')

In [8]:
dataset.dtypes

sl_no               int64
gender             object
ssc_p             float64
ssc_b              object
hsc_p             float64
hsc_b              object
hsc_s              object
degree_p          float64
degree_t           object
workex             object
etest_p           float64
specialisation     object
mba_p             float64
status             object
salary            float64
dtype: object

In [9]:
dataset["gender"].dtypes

dtype('O')

In [10]:
dataset["ssc_p"].dtypes

dtype('float64')

# Logic to separate Quantitative and Qualitative Manually

In [11]:
for ColumnName in dataset.columns:
    print(ColumnName)

sl_no
gender
ssc_p
ssc_b
hsc_p
hsc_b
hsc_s
degree_p
degree_t
workex
etest_p
specialisation
mba_p
status
salary

In [12]:
if (dataset["ssc_p"].dtypes=="O"):
    print("Qual")
else:
    print("Quan")

Quan

# Logic to separate Quantitative and Qualitative Automatically

In [13]:
#Creating a empty list and check the conditions using for loop
# Approach 1:

Quan=[]
Qual=[]
for ColumnName in dataset.columns:
    print(ColumnName)
    if (dataset[ColumnName].dtypes=="O"):
        print("Qual")
    else:
        print("Quan")

sl_no
Quan
gender
Qual
ssc_p
Quan
ssc_b
Qual
hsc_p
Quan
hsc_b
Qual
hsc_s
Qual
degree_p
Quan
degree_t
Qual
workex
Qual
etest_p
Quan
specialisation
Qual
mba_p
Quan
status
Qual
salary
Quan

In [14]:
#Using append() method - Appends a element to the end of the list
# Approach 2:

Quan=[]
Qual=[]
for ColumnName in dataset.columns:
    print(ColumnName)
    if (dataset[ColumnName].dtypes=="O"):  # "O" is Object Data type
        print("Qual")
        Qual.append(ColumnName)
    else:
        print("Quan")
        Quan.append(ColumnName)

sl_no
Quan
gender
Qual
ssc_p
Quan
ssc_b
Qual
hsc_p
Quan
hsc_b
Qual
hsc_s
Qual
degree_p
Quan
degree_t
Qual
workex
Qual
etest_p
Quan
specialisation
Qual
mba_p
Quan
status
Qual
salary
Quan

In [15]:
Quan

['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary']

In [16]:
Qual

['gender',
 'ssc_b',
 'hsc_b',
 'hsc_s',
 'degree_t',
 'workex',
 'specialisation',
 'status']

# Logic to separate Quan and Qual Automatically using Function

In [17]:
def QuanQual(dataset):
    Quan=[]
    Qual=[]
    for ColumnName in dataset.columns:
        #print(ColumnName)
        if (dataset[ColumnName].dtypes=="O"):
            #print("Qual")
            Qual.append(ColumnName)
        else:
            #print("Quan")
            Quan.append(ColumnName)
    return Quan,Qual                 #Calling QuanQual() function.

In [18]:
QuanQual(dataset)

(['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary'],
 ['gender',
  'ssc_b',
  'hsc_b',
  'hsc_s',
  'degree_t',
  'workex',
  'specialisation',
  'status'])

In [19]:
Quan, Qual = QuanQual(dataset)

In [20]:
Quan

['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary']

In [21]:
Qual

['gender',
 'ssc_b',
 'hsc_b',
 'hsc_s',
 'degree_t',
 'workex',
 'specialisation',
 'status']

# MEASURE OF CENTRAL TENDENCY
# Mean, Median Mode

In [22]:
# Finding Mean, Median and Mode for 'ssc_p' column

round(dataset["ssc_p"].mean())    # Mean is the average

67

In [23]:
int(dataset["ssc_p"].median())    # Median is the midpoint the data

67

In [24]:
int(dataset["ssc_p"].mode()[0])   # Mode is the repitive data

62

In [25]:
dataset.describe()   # To view mean, median, mode for the dataset

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
count,215.000000,215.000000,215.000000,215.000000,215.000000,215.000000,148.000000
mean,108.000000,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
std,62.209324,10.827205,10.897509,7.358743,13.275956,5.833385,93457.452420
min,1.000000,40.890000,37.000000,50.000000,50.000000,51.210000,200000.000000
25%,54.500000,60.600000,60.900000,61.000000,60.000000,57.945000,240000.000000
50%,108.000000,67.000000,65.000000,66.000000,71.000000,62.000000,265000.000000
75%,161.500000,75.700000,73.000000,72.000000,83.500000,66.255000,300000.000000
max,215.000000,89.400000,97.700000,91.000000,98.000000,77.890000,940000.000000

In [26]:
descriptive = pd.DataFrame()  # Creates an empty table and assigned to variable descriptive

In [27]:
descriptive

Empty DataFrame
Columns: []
Index: []

In [28]:
descriptive = pd.DataFrame(index=["Mean", "Median", "Mode"]) # Creates a table with only index.

In [29]:
descriptive

Empty DataFrame
Columns: []
Index: [Mean, Median, Mode]

In [30]:
descriptive = pd.DataFrame(index=["Mean", "Median", "Mode"], columns=Quan)  # Now it creates a table of Index and Columns with NaN values.

In [31]:
descriptive

       sl_no ssc_p hsc_p degree_p etest_p mba_p salary
Mean     NaN   NaN   NaN      NaN     NaN   NaN    NaN
Median   NaN   NaN   NaN      NaN     NaN   NaN    NaN
Mode     NaN   NaN   NaN      NaN     NaN   NaN    NaN

In [32]:
descriptive.loc["hsc_p", "Median"]=0  # Assign values for a particular Row-index, column

In [33]:
descriptive

       sl_no ssc_p hsc_p degree_p etest_p mba_p salary  Median
Mean     NaN   NaN   NaN      NaN     NaN   NaN    NaN     NaN
Median   NaN   NaN   NaN      NaN     NaN   NaN    NaN     NaN
Mode     NaN   NaN   NaN      NaN     NaN   NaN    NaN     NaN
hsc_p    NaN   NaN   NaN      NaN     NaN   NaN    NaN     0.0

In [34]:
descriptive = pd.DataFrame(index=["Mean", "Median", "Mode"], columns=Quan)
for ColumnName in Quan:
    descriptive[ColumnName]["Mean"]=dataset[ColumnName].mean()

In [35]:
descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
Median,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Mode,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
descriptive = pd.DataFrame(index=["Mean", "Median", "Mode"], columns=Quan)
for ColumnName in Quan:
    descriptive[ColumnName]["Mean"]=dataset[ColumnName].mean()
    descriptive[ColumnName]["Median"]=dataset[ColumnName].median()

In [37]:
descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
descriptive = pd.DataFrame(index=["Mean", "Median", "Mode"], columns=Quan)
for ColumnName in Quan:
    descriptive[ColumnName]["Mean"]=dataset[ColumnName].mean()
    descriptive[ColumnName]["Median"]=dataset[ColumnName].median()
    descriptive[ColumnName]["Mode"]=dataset[ColumnName].mode()[0]

In [39]:
descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0

# MEASURE OF LOCATION OF DATA

# Percentile

In [40]:
import numpy as np    # numpy library is used in panda to retrieve the percentile for the dataset

In [41]:
np.percentile(dataset["ssc_p"],10)

np.float64(52.0)

In [42]:
float(np.percentile(dataset["ssc_p"], 10)) 

# np.percentile(column_data,percentile). This returns result without handling  missing values (Nan) 
# 10% of the data is within 52 score in SSC.
# we can calculate the percentile value for the 4 quadrant (25, 50, 75, 100)

52.0

In [43]:
descriptive = pd.DataFrame(index=["Mean", "Median", "Mode", "Q1:25%", "Q2:50%", "Q3:75%", "Q4:100"], columns=Quan)
for ColumnName in Quan:
    descriptive[ColumnName]["Mean"]=dataset[ColumnName].mean()
    descriptive[ColumnName]["Median"]=dataset[ColumnName].median()
    descriptive[ColumnName]["Mode"]=dataset[ColumnName].mode()[0]

In [44]:
descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0
Q1:25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Q2:50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Q3:75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Q4:100,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [45]:
descriptive = pd.DataFrame(index=["Mean", "Median", "Mode", "Q1:25%", "Q2:50%", "Q3:75%", "99%", "Q4:100%"], columns=Quan)
for ColumnName in Quan:
    descriptive[ColumnName]["Mean"] = dataset[ColumnName].mean()
    descriptive[ColumnName]["Median"] = dataset[ColumnName].median()
    descriptive[ColumnName]["Mode"] = dataset[ColumnName].mode()[0]
    descriptive[ColumnName]["Q1:25%"] = dataset.describe()[ColumnName]["25%"]
    descriptive[ColumnName]["Q2:50%"] = dataset.describe()[ColumnName]["50%"]
    descriptive[ColumnName]["Q3:75%"] = dataset.describe()[ColumnName]["75%"]
    descriptive[ColumnName]["99%"] = float(np.percentile(dataset[ColumnName],[99]))
    descriptive[ColumnName]["Q4:100%"] = dataset.describe()[ColumnName]["max"]

In [46]:
descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0
Q1:25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2:50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3:75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
99%,212.86,87.0,91.86,83.86,97.0,76.1142,NaN
Q4:100%,215.0,89.4,97.7,91.0,98.0,77.89,940000.0

# IQR - Interquartile Range

In [47]:
descriptive = pd.DataFrame(index=["Mean", "Median", "Mode", "Q1:25%", "Q2:50%", "Q3:75%", "99%", "Q4:100%", 
                                  "IQR", "1.5rule", "Lower_Bound", "Upper_Bound", "Min", "Max"], columns=Quan)
for ColumnName in Quan:
    descriptive[ColumnName]["Mean"] = dataset[ColumnName].mean()
    descriptive[ColumnName]["Median"] = dataset[ColumnName].median()
    descriptive[ColumnName]["Mode"] = dataset[ColumnName].mode()[0]
    descriptive[ColumnName]["Q1:25%"] = dataset.describe()[ColumnName]["25%"]
    descriptive[ColumnName]["Q2:50%"] = dataset.describe()[ColumnName]["50%"]
    descriptive[ColumnName]["Q3:75%"] = dataset.describe()[ColumnName]["75%"]
    descriptive[ColumnName]["99%"] = float(np.percentile(dataset[ColumnName],[99]))
    descriptive[ColumnName]["Q4:100%"] = dataset.describe()[ColumnName]["max"]
    descriptive[ColumnName]["IQR"] = descriptive[ColumnName]["Q3:75%"] -  descriptive[ColumnName]["Q1:25%"]
    descriptive[ColumnName]["1.5rule"] = 1.5 * descriptive[ColumnName]["IQR"]
    descriptive[ColumnName]["Lower_Bound"] = descriptive[ColumnName]["Q1:25%"] - descriptive[ColumnName]["1.5rule"]
    descriptive[ColumnName]["Upper_Bound"] = descriptive[ColumnName]["Q3:75%"] + descriptive[ColumnName]["1.5rule"]
    descriptive[ColumnName]["Min"] = dataset[ColumnName].min()
    descriptive[ColumnName]["Max"] = dataset[ColumnName].max()

In [48]:
descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0
Q1:25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2:50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3:75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
99%,212.86,87.0,91.86,83.86,97.0,76.1142,NaN
Q4:100%,215.0,89.4,97.7,91.0,98.0,77.89,940000.0
IQR,107.0,15.1,12.1,11.0,23.5,8.31,60000.0
1.5rule,160.5,22.65,18.15,16.5,35.25,12.465,90000.0
Lower_Bound,-106.0,37.95,42.75,44.5,24.75,45.48,150000.0
Upper_Bound,322.0,98.35,91.15,88.5,118.75,78.72,390000.0
Min,1,40.89,37.0,50.0,50.0,51.21,200000.0
Max,215,89.4,97.7,91.0,98.0,77.89,940000.0

# Finding Outliers in Columns

In [49]:
descriptive["hsc_p"]["Min"] < descriptive["hsc_p"]["Lower_Bound"]  # dataset[column][row_condition]

np.True_

In [50]:
lesser = []
greater = []

for ColumnName in Quan:
    if(descriptive[ColumnName]["Min"] < descriptive[ColumnName]["Lower_Bound"]):
        lesser.append(ColumnName)
    if(descriptive[ColumnName]["Max"] > descriptive[ColumnName]["Upper_Bound"]):
        greater.append(ColumnName)

In [51]:
lesser

['hsc_p']

In [52]:
greater

['hsc_p', 'degree_p', 'salary']

# Replace Outliers in Columns

In [53]:
# Replace Outliers

for ColumnName in lesser:
    dataset[ColumnName][dataset[ColumnName] < descriptive[ColumnName]["Lower_Bound"]]=descriptive[ColumnName]["Lower_Bound"]
for ColumnName in greater:
    dataset[ColumnName][dataset[ColumnName] > descriptive[ColumnName]["Upper_Bound"]]=descriptive[ColumnName]["Upper_Bound"]

In [54]:
descriptive = pd.DataFrame(index=["Mean", "Median", "Mode", "Q1:25%", "Q2:50%", "Q3:75%", "99%", "Q4:100%", 
                                  "IQR", "1.5rule", "Lower_Bound", "Upper_Bound", "Min", "Max"], columns=Quan)
for ColumnName in Quan:
    descriptive[ColumnName]["Mean"] = dataset[ColumnName].mean()
    descriptive[ColumnName]["Median"] = dataset[ColumnName].median()
    descriptive[ColumnName]["Mode"] = dataset[ColumnName].mode()[0]
    descriptive[ColumnName]["Q1:25%"] = dataset.describe()[ColumnName]["25%"]
    descriptive[ColumnName]["Q2:50%"] = dataset.describe()[ColumnName]["50%"]
    descriptive[ColumnName]["Q3:75%"] = dataset.describe()[ColumnName]["75%"]
    descriptive[ColumnName]["99%"] = float(np.percentile(dataset[ColumnName],[99]))
    descriptive[ColumnName]["Q4:100%"] = dataset.describe()[ColumnName]["max"]
    descriptive[ColumnName]["IQR"] = descriptive[ColumnName]["Q3:75%"] -  descriptive[ColumnName]["Q1:25%"]
    descriptive[ColumnName]["1.5rule"] = 1.5 * descriptive[ColumnName]["IQR"]
    descriptive[ColumnName]["Lower_Bound"] = descriptive[ColumnName]["Q1:25%"] - descriptive[ColumnName]["1.5rule"]
    descriptive[ColumnName]["Upper_Bound"] = descriptive[ColumnName]["Q3:75%"] + descriptive[ColumnName]["1.5rule"]
    descriptive[ColumnName]["Min"] = dataset[ColumnName].min()
    descriptive[ColumnName]["Max"] = dataset[ColumnName].max()

In [55]:
descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.334744,66.358558,72.100558,62.278186,277648.648649
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0
Q1:25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2:50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3:75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
99%,212.86,87.0,91.129,83.86,97.0,76.1142,NaN
Q4:100%,215.0,89.4,91.15,88.5,98.0,77.89,390000.0
IQR,107.0,15.1,12.1,11.0,23.5,8.31,60000.0
1.5rule,160.5,22.65,18.15,16.5,35.25,12.465,90000.0
Lower_Bound,-106.0,37.95,42.75,44.5,24.75,45.48,150000.0
Upper_Bound,322.0,98.35,91.15,88.5,118.75,78.72,390000.0
Min,1,40.89,42.75,50.0,50.0,51.21,200000.0
Max,215,89.4,91.15,88.5,98.0,77.89,390000.0

In [56]:
# check outliers after replacing

lesser = []
greater = []

for ColumnName in Quan:
    if(descriptive[ColumnName]["Lower_Bound"] > descriptive[ColumnName]["Min"]):
        lesser.append(ColumnName)
    if(descriptive[ColumnName]["Upper_Bound"] < descriptive[ColumnName]["Max"]):
        greater.append(ColumnName)

In [57]:
lesser

[]

In [58]:
greater

[]

# Frequency

In [59]:
dataset["ssc_p"].value_counts()
# dataset["ssc_p"].value_counts().index
# dataset["ssc_p"].value_counts().values
# dataset["ssc_p"].value_counts().sort_values

ssc_p
62.00    11
63.00    10
67.00     9
52.00     9
73.00     9
         ..
69.70     1
80.92     1
83.00     1
86.50     1
80.60     1
Name: count, Length: 103, dtype: int64

In [60]:
Frequency_Table = pd.DataFrame(columns=("Unique_values", "Frequency", "Relative_Frequency", "Cumsum"))

In [61]:
Frequency_Table

Empty DataFrame
Columns: [Unique_values, Frequency, Relative_Frequency, Cumsum]
Index: []

In [62]:
Frequency_Table["Unique_values"] = dataset["ssc_p"].value_counts().index

In [63]:
Frequency_Table

     Unique_values Frequency Relative_Frequency Cumsum
0            62.00       NaN                NaN    NaN
1            63.00       NaN                NaN    NaN
2            67.00       NaN                NaN    NaN
3            52.00       NaN                NaN    NaN
4            73.00       NaN                NaN    NaN
..             ...       ...                ...    ...
98           69.70       NaN                NaN    NaN
99           80.92       NaN                NaN    NaN
100          83.00       NaN                NaN    NaN
101          86.50       NaN                NaN    NaN
102          80.60       NaN                NaN    NaN

[103 rows x 4 columns]

In [64]:
Length_Count = len(dataset["ssc_p"].value_counts())  # To view the length

In [65]:
Frequency_Table["Unique_values"] = dataset["ssc_p"].value_counts().index
Frequency_Table["Frequency"] = dataset["ssc_p"].value_counts().values
Frequency_Table["Relative_Frequency"] = (Frequency_Table["Frequency"] / Length_Count)
Frequency_Table["Cumsum"] = Frequency_Table["Relative_Frequency"].cumsum()

In [66]:
Frequency_Table

     Unique_values  Frequency  Relative_Frequency    Cumsum
0            62.00         11            0.106796  0.106796
1            63.00         10            0.097087  0.203883
2            67.00          9            0.087379  0.291262
3            52.00          9            0.087379  0.378641
4            73.00          9            0.087379  0.466019
..             ...        ...                 ...       ...
98           69.70          1            0.009709  2.048544
99           80.92          1            0.009709  2.058252
100          83.00          1            0.009709  2.067961
101          86.50          1            0.009709  2.077670
102          80.60          1            0.009709  2.087379

[103 rows x 4 columns]

In [67]:
# Creating Function for Frequency Table 

def Frequency_Table(ColumnName, dataset):
    Frequency_Table = pd.DataFrame(columns=("Unique_values", "Frequency", "Relative_Frequency", "Cumsum"))
    Frequency_Table["Unique_values"] = dataset[ColumnName].value_counts().index
    Frequency_Table["Frequency"] = dataset[ColumnName].value_counts().values
    Frequency_Table["Relative_Frequency"] = (Frequency_Table["Frequency"] / Length_Count)
    Frequency_Table["Cumsum"] = Frequency_Table["Relative_Frequency"].cumsum()
    return Frequency_Table

In [68]:
Frequency_Table("hsc_p", dataset)

    Unique_values  Frequency  Relative_Frequency    Cumsum
0           63.00         14            0.135922  0.135922
1           62.00         12            0.116505  0.252427
2           60.00          9            0.087379  0.339806
3           67.00          9            0.087379  0.427184
4           70.00          8            0.077670  0.504854
..            ...        ...                 ...       ...
86          70.29          1            0.009709  2.048544
87          83.83          1            0.009709  2.058252
88          70.40          1            0.009709  2.067961
89          90.90          1            0.009709  2.077670
90          61.33          1            0.009709  2.087379

[91 rows x 4 columns]

In [69]:
Frequency_Table("degree_p", dataset)

    Unique_values  Frequency  Relative_Frequency    Cumsum
0            65.0         20            0.194175  0.194175
1            66.0         13            0.126214  0.320388
2            72.0         12            0.116505  0.436893
3            64.0         11            0.106796  0.543689
4            58.0          9            0.087379  0.631068
..            ...        ...                 ...       ...
84           82.0          1            0.009709  2.048544
85           50.8          1            0.009709  2.058252
86           76.0          1            0.009709  2.067961
87           63.0          1            0.009709  2.077670
88           77.6          1            0.009709  2.087379

[89 rows x 4 columns]

In [70]:
Frequency_Table("etest_p", dataset)

    Unique_values  Frequency  Relative_Frequency    Cumsum
0           60.00         14            0.135922  0.135922
1           80.00          8            0.077670  0.213592
2           75.00          7            0.067961  0.281553
3           67.00          7            0.067961  0.349515
4           55.00          6            0.058252  0.407767
..            ...        ...                 ...       ...
95          95.46          1            0.009709  2.048544
96          93.91          1            0.009709  2.058252
97          56.39          1            0.009709  2.067961
98          57.50          1            0.009709  2.077670
99          91.00          1            0.009709  2.087379

[100 rows x 4 columns]

In [71]:
Frequency_Table("mba_p", dataset)

     Unique_values  Frequency  Relative_Frequency    Cumsum
0            56.70          3            0.029126  0.029126
1            66.94          2            0.019417  0.048544
2            59.47          2            0.019417  0.067961
3            60.44          2            0.019417  0.087379
4            68.07          2            0.019417  0.106796
..             ...        ...                 ...       ...
200          67.00          1            0.009709  2.048544
201          64.27          1            0.009709  2.058252
202          57.65          1            0.009709  2.067961
203          59.42          1            0.009709  2.077670
204          60.22          1            0.009709  2.087379

[205 rows x 4 columns]

In [72]:
Frequency_Table("salary", dataset)

    Unique_values  Frequency  Relative_Frequency    Cumsum
0        300000.0         22            0.213592  0.213592
1        250000.0         18            0.174757  0.388350
2        390000.0         15            0.145631  0.533981
3        240000.0         15            0.145631  0.679612
4        260000.0          7            0.067961  0.747573
5        200000.0          6            0.058252  0.805825
6        265000.0          6            0.058252  0.864078
7        360000.0          6            0.058252  0.922330
8        275000.0          5            0.048544  0.970874
9        220000.0          5            0.048544  1.019417
10       270000.0          4            0.038835  1.058252
11       210000.0          4            0.038835  1.097087
12       350000.0          3            0.029126  1.126214
13       216000.0          3            0.029126  1.155340
14       204000.0          2            0.019417  1.174757
15       236000.0          2            0.019417  1.194175
16       218000.0          2            0.019417  1.213592
17       230000.0          2            0.019417  1.233010
18       252000.0          2            0.019417  1.252427
19       280000.0          2            0.019417  1.271845
20       276000.0          2            0.019417  1.291262
21       278000.0          1            0.009709  1.300971
22       233000.0          1            0.009709  1.310680
23       264000.0          1            0.009709  1.320388
24       290000.0          1            0.009709  1.330097
25       285000.0          1            0.009709  1.339806
26       255000.0          1            0.009709  1.349515
27       340000.0          1            0.009709  1.359223
28       380000.0          1            0.009709  1.368932
29       225000.0          1            0.009709  1.378641
30       320000.0          1            0.009709  1.388350
31       336000.0          1            0.009709  1.398058
32       231000.0          1            0.009709  1.407767
33       268000.0          1            0.009709  1.417476
34       287000.0          1            0.009709  1.427184
35       295000.0          1            0.009709  1.436893

In [73]:
# Creating Function for Univariate

def Univariate(dataset, Quan):
    descriptive = pd.DataFrame(index=["Mean", "Median", "Mode", "Q1:25%", "Q2:50%", "Q3:75%", "99%", "Q4:100%", 
                                  "IQR", "1.5rule", "Lower_Bound", "Upper_Bound", "Min", "Max"], columns=Quan)
    for ColumnName in Quan:
        descriptive[ColumnName]["Mean"] = dataset[ColumnName].mean()
        descriptive[ColumnName]["Median"] = dataset[ColumnName].median()
        descriptive[ColumnName]["Mode"] = dataset[ColumnName].mode()[0]
        descriptive[ColumnName]["Q1:25%"] = dataset.describe()[ColumnName]["25%"]
        descriptive[ColumnName]["Q2:50%"] = dataset.describe()[ColumnName]["50%"]
        descriptive[ColumnName]["Q3:75%"] = dataset.describe()[ColumnName]["75%"]
        descriptive[ColumnName]["99%"] = float(np.percentile(dataset[ColumnName],[99]))
        descriptive[ColumnName]["Q4:100%"] = dataset.describe()[ColumnName]["max"]
        descriptive[ColumnName]["IQR"] = descriptive[ColumnName]["Q3:75%"] -  descriptive[ColumnName]["Q1:25%"]
        descriptive[ColumnName]["1.5rule"] = 1.5 * descriptive[ColumnName]["IQR"]
        descriptive[ColumnName]["Lower_Bound"] = descriptive[ColumnName]["Q1:25%"] - descriptive[ColumnName]["1.5rule"]
        descriptive[ColumnName]["Upper_Bound"] = descriptive[ColumnName]["Q3:75%"] + descriptive[ColumnName]["1.5rule"]
        descriptive[ColumnName]["Min"] = dataset[ColumnName].min()
        descriptive[ColumnName]["Max"] = dataset[ColumnName].max()
        
    return descriptive

In [74]:
Univariate(dataset, Quan)

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.334744,66.358558,72.100558,62.278186,277648.648649
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0
Q1:25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2:50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3:75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
99%,212.86,87.0,91.129,83.86,97.0,76.1142,NaN
Q4:100%,215.0,89.4,91.15,88.5,98.0,77.89,390000.0
IQR,107.0,15.1,12.1,11.0,23.5,8.31,60000.0
1.5rule,160.5,22.65,18.15,16.5,35.25,12.465,90000.0
Lower_Bound,-106.0,37.95,42.75,44.5,24.75,45.48,150000.0
Upper_Bound,322.0,98.35,91.15,88.5,118.75,78.72,390000.0
Min,1,40.89,42.75,50.0,50.0,51.21,200000.0
Max,215,89.4,91.15,88.5,98.0,77.89,390000.0

In [75]:
# Creating function for finding outliers 

def Find_Outlier(descriptive, Quan):
    lesser = []
    greater = []
    for ColumnName in Quan:
        if(descriptive[ColumnName]["Min"] < descriptive[ColumnName]["Lower_Bound"]):
            lesser.append(ColumnName)
        if(descriptive[ColumnName]["Max"] > descriptive[ColumnName]["Upper_Bound"]):
            greater.append(ColumnName)
    return lesser, greater

In [76]:
Find_Outlier(descriptive, Quan)

([], [])

In [77]:
# Creating function for replacing outliers 

def Replace_Outlier(descriptive, Quan):
    for ColumnName in lesser:
        dataset[ColumnName][dataset[ColumnName] < descriptive[ColumnName]["Lower_Bound"]]=descriptive[ColumnName]["Lower_Bound"]
    for ColumnName in greater:
        dataset[ColumnName][dataset[ColumnName] > descriptive[ColumnName]["Upper_Bound"]]=descriptive[ColumnName]["Upper_Bound"]
    return descriptive

In [78]:
Replace_Outlier(descriptive, Quan)

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.334744,66.358558,72.100558,62.278186,277648.648649
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0
Q1:25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2:50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3:75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
99%,212.86,87.0,91.129,83.86,97.0,76.1142,NaN
Q4:100%,215.0,89.4,91.15,88.5,98.0,77.89,390000.0
IQR,107.0,15.1,12.1,11.0,23.5,8.31,60000.0
1.5rule,160.5,22.65,18.15,16.5,35.25,12.465,90000.0
Lower_Bound,-106.0,37.95,42.75,44.5,24.75,45.48,150000.0
Upper_Bound,322.0,98.35,91.15,88.5,118.75,78.72,390000.0
Min,1,40.89,42.75,50.0,50.0,51.21,200000.0
Max,215,89.4,91.15,88.5,98.0,77.89,390000.0

# Histogram, Skewness, Kurtosis

In [83]:
dir(dataset["ssc_p"]) # To check libraries

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__bool__',
 '__class__',
 '__column_consortium_standard__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__firstlineno__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_as_manager',
 '_attrs',
 '_binop',
 '_cacher',
 '_can_hold_na',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_expanddim_from_mgr',
 '_constructor_from_mgr',
 '_data',
 '_deprecate_downcast',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_duplicated',
 '_find_valid_index',
 '_flags',
 '_flex_method',
 '_from_mgr',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cacher',
 '_get_cleaned_column_resolvers',
 '_get_index_resolvers',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_rows_with_mask',
 '_get_value',
 '_get_values_tuple',
 '_get_with',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_init_dict',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_cached',
 '_is_copy',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_is_view_after_cow_rules',
 '_item_cache',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_map_values',
 '_maybe_update_cacher',
 '_memory_usage',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_name',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_protect_consolidate',
 '_reduce',
 '_references',
 '_reindex_axes',
 '_reindex_indexer',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_single',
 '_repr_data_resource_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_set_as_cached',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_labels',
 '_set_name',
 '_set_value',
 '_set_values',
 '_set_with',
 '_set_with_engine',
 '_shift_with_freq',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'argmax',
 'argmin',
 'argsort',
 'array',
 'asfreq',
 'asof',
 'astype',
 'at',
 'at_time',
 'attrs',
 'autocorr',
 'axes',
 'backfill',
 'between',
 'between_time',
 'bfill',
 'bool',
 'case_when',
 'clip',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'divmod',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtype',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'ewm',
 'expanding',
 'explode',
 'factorize',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'ge',
 'get',
 'groupby',
 'gt',
 'hasnans',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'interpolate',
 'is_monotonic_decreasing',
 'is_monotonic_increasing',
 'is_unique',
 'isin',
 'isna',
 'isnull',
 'item',
 'items',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'list',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'memory_usage',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'name',
 'nbytes',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pipe',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'radd',
 'rank',
 'ravel',
 'rdiv',
 'rdivmod',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'repeat',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'searchsorted',
 'sem',
 'set_axis',
 'set_flags',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'std',
 'struct',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_frame',
 'to_hdf',
 'to_json',
 'to_latex',
 'to_list',
 'to_markdown',
 'to_numpy',
 'to_period',
 'to_pickle',
 'to_sql',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unique',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'view',
 'where',
 'xs']

In [85]:
dataset["ssc_p"].skew()

np.float64(-0.13264949031456927)

In [86]:
dataset["ssc_p"].kurtosis()

np.float64(-0.6075102066986688)

In [87]:
def Univariate(dataset, Quan):
    descriptive = pd.DataFrame(index=["Mean", "Median", "Mode", "Q1:25%", "Q2:50%", "Q3:75%", "99%", "Q4:100%", 
                                  "IQR", "1.5rule", "Lower_Bound", "Upper_Bound", "Min", "Max", "skew", "kurtosis"], columns=Quan)
    for ColumnName in Quan:
        descriptive[ColumnName]["Mean"] = dataset[ColumnName].mean()
        descriptive[ColumnName]["Median"] = dataset[ColumnName].median()
        descriptive[ColumnName]["Mode"] = dataset[ColumnName].mode()[0]
        descriptive[ColumnName]["Q1:25%"] = dataset.describe()[ColumnName]["25%"]
        descriptive[ColumnName]["Q2:50%"] = dataset.describe()[ColumnName]["50%"]
        descriptive[ColumnName]["Q3:75%"] = dataset.describe()[ColumnName]["75%"]
        descriptive[ColumnName]["99%"] = float(np.percentile(dataset[ColumnName],[99]))
        descriptive[ColumnName]["Q4:100%"] = dataset.describe()[ColumnName]["max"]
        descriptive[ColumnName]["IQR"] = descriptive[ColumnName]["Q3:75%"] -  descriptive[ColumnName]["Q1:25%"]
        descriptive[ColumnName]["1.5rule"] = 1.5 * descriptive[ColumnName]["IQR"]
        descriptive[ColumnName]["Lower_Bound"] = descriptive[ColumnName]["Q1:25%"] - descriptive[ColumnName]["1.5rule"]
        descriptive[ColumnName]["Upper_Bound"] = descriptive[ColumnName]["Q3:75%"] + descriptive[ColumnName]["1.5rule"]
        descriptive[ColumnName]["Min"] = dataset[ColumnName].min()
        descriptive[ColumnName]["Max"] = dataset[ColumnName].max()
        descriptive[ColumnName]["skew"] = dataset[ColumnName].skew()
        descriptive[ColumnName]["kurtosis"] = dataset[ColumnName].kurtosis()
        
    return descriptive

In [88]:
Univariate(dataset, Quan)

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.334744,66.358558,72.100558,62.278186,277648.648649
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0
Q1:25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2:50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3:75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
99%,212.86,87.0,91.129,83.86,97.0,76.1142,NaN
Q4:100%,215.0,89.4,91.15,88.5,98.0,77.89,390000.0
IQR,107.0,15.1,12.1,11.0,23.5,8.31,60000.0
1.5rule,160.5,22.65,18.15,16.5,35.25,12.465,90000.0
Lower_Bound,-106.0,37.95,42.75,44.5,24.75,45.48,150000.0
Upper_Bound,322.0,98.35,91.15,88.5,118.75,78.72,390000.0
Min,1,40.89,42.75,50.0,50.0,51.21,200000.0
Max,215,89.4,91.15,88.5,98.0,77.89,390000.0
skew,0.0,-0.132649,0.162611,0.204164,0.282308,0.313576,0.8067
kurtosis,-1.2,-0.60751,0.086901,-0.09749,-1.08858,-0.470723,-0.239837