In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("kidney_disease.csv")

In [3]:
dataset

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,53,6800,6.1,no,no,no,good,no,no,notckd

# Finding missing values in dataset

In [4]:
dataset.isnull().sum()

id                  0
age                 9
bp                 12
sg                 47
al                 46
su                 49
rbc               152
pc                 65
pcc                 4
ba                  4
bgr                44
bu                 19
sc                 17
sod                87
pot                88
hemo               52
pcv                70
wc                105
rc                130
htn                 2
dm                  2
cad                 2
appet               1
pe                  1
ane                 1
classification      0
dtype: int64

# Seperate Quan and Qual using Function

In [5]:
def QuanQual(dataset):
    Quan=[]
    Qual=[]
    for ColumnName in dataset.columns:
        if (dataset[ColumnName].dtypes=="O"):
            Qual.append(ColumnName)
        else:
            Quan.append(ColumnName)
    return Quan,Qual

In [6]:
Quan,Qual = QuanQual(dataset)

In [7]:
print("Quantitative columns:", Quan)
print("Qualitative columns:", Qual)

Quantitative columns: ['id', 'age', 'bp', 'sg', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hemo']
Qualitative columns: ['rbc', 'pc', 'pcc', 'ba', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad', 'appet', 'pe', 'ane', 'classification']

In [8]:
Quan, Qual = QuanQual(dataset)

In [9]:
dataset[Quan]

      id   age    bp     sg   al   su    bgr    bu   sc    sod  pot  hemo
0      0  48.0  80.0  1.020  1.0  0.0  121.0  36.0  1.2    NaN  NaN  15.4
1      1   7.0  50.0  1.020  4.0  0.0    NaN  18.0  0.8    NaN  NaN  11.3
2      2  62.0  80.0  1.010  2.0  3.0  423.0  53.0  1.8    NaN  NaN   9.6
3      3  48.0  70.0  1.005  4.0  0.0  117.0  56.0  3.8  111.0  2.5  11.2
4      4  51.0  80.0  1.010  2.0  0.0  106.0  26.0  1.4    NaN  NaN  11.6
..   ...   ...   ...    ...  ...  ...    ...   ...  ...    ...  ...   ...
395  395  55.0  80.0  1.020  0.0  0.0  140.0  49.0  0.5  150.0  4.9  15.7
396  396  42.0  70.0  1.025  0.0  0.0   75.0  31.0  1.2  141.0  3.5  16.5
397  397  12.0  80.0  1.020  0.0  0.0  100.0  26.0  0.6  137.0  4.4  15.8
398  398  17.0  60.0  1.025  0.0  0.0  114.0  50.0  1.0  135.0  4.9  14.2
399  399  58.0  80.0  1.025  0.0  0.0  131.0  18.0  1.1  141.0  3.5  15.8

[400 rows x 12 columns]

# Replacing Quan Missing/Null values with SimpleImputer

In [10]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy='median')
imp.fit(dataset[Quan])
Quan_dataset = imp.fit_transform(dataset[Quan])
Quan_dataset

array([[  0. ,  48. ,  80. , ..., 138. ,   4.4,  15.4],
       [  1. ,   7. ,  50. , ..., 138. ,   4.4,  11.3],
       [  2. ,  62. ,  80. , ..., 138. ,   4.4,   9.6],
       ...,
       [397. ,  12. ,  80. , ..., 137. ,   4.4,  15.8],
       [398. ,  17. ,  60. , ..., 135. ,   4.9,  14.2],
       [399. ,  58. ,  80. , ..., 141. ,   3.5,  15.8]], shape=(400, 12))

In [11]:
Quan_dataset = pd.DataFrame(Quan_dataset, columns=Quan)
Quan_dataset

        id   age    bp     sg   al   su    bgr    bu   sc    sod  pot  hemo
0      0.0  48.0  80.0  1.020  1.0  0.0  121.0  36.0  1.2  138.0  4.4  15.4
1      1.0   7.0  50.0  1.020  4.0  0.0  121.0  18.0  0.8  138.0  4.4  11.3
2      2.0  62.0  80.0  1.010  2.0  3.0  423.0  53.0  1.8  138.0  4.4   9.6
3      3.0  48.0  70.0  1.005  4.0  0.0  117.0  56.0  3.8  111.0  2.5  11.2
4      4.0  51.0  80.0  1.010  2.0  0.0  106.0  26.0  1.4  138.0  4.4  11.6
..     ...   ...   ...    ...  ...  ...    ...   ...  ...    ...  ...   ...
395  395.0  55.0  80.0  1.020  0.0  0.0  140.0  49.0  0.5  150.0  4.9  15.7
396  396.0  42.0  70.0  1.025  0.0  0.0   75.0  31.0  1.2  141.0  3.5  16.5
397  397.0  12.0  80.0  1.020  0.0  0.0  100.0  26.0  0.6  137.0  4.4  15.8
398  398.0  17.0  60.0  1.025  0.0  0.0  114.0  50.0  1.0  135.0  4.9  14.2
399  399.0  58.0  80.0  1.025  0.0  0.0  131.0  18.0  1.1  141.0  3.5  15.8

[400 rows x 12 columns]

In [13]:
Quan_dataset.isnull().sum()

id      0
age     0
bp      0
sg      0
al      0
su      0
bgr     0
bu      0
sc      0
sod     0
pot     0
hemo    0
dtype: int64

# Replacing Qual Missing/Null values with SimpleImputer

In [16]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy='constant', fill_value='Unknown')
imp.fit(dataset[Qual])
Qual_dataset = imp.fit_transform(dataset[Qual])
Qual_dataset

array([['Unknown', 'normal', 'notpresent', ..., 'no', 'no', 'ckd'],
       ['Unknown', 'normal', 'notpresent', ..., 'no', 'no', 'ckd'],
       ['normal', 'normal', 'notpresent', ..., 'no', 'yes', 'ckd'],
       ...,
       ['normal', 'normal', 'notpresent', ..., 'no', 'no', 'notckd'],
       ['normal', 'normal', 'notpresent', ..., 'no', 'no', 'notckd'],
       ['normal', 'normal', 'notpresent', ..., 'no', 'no', 'notckd']],
      shape=(400, 14), dtype=object)

In [17]:
Qual_dataset = pd.DataFrame(Qual_dataset, columns=Qual)
Qual_dataset

,rbc,pc,pcc,ba,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,Unknown,normal,notpresent,notpresent,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,Unknown,normal,notpresent,notpresent,38,6000,Unknown,no,no,no,good,no,no,ckd
2,normal,normal,notpresent,notpresent,31,7500,Unknown,no,yes,no,poor,no,yes,ckd
3,normal,abnormal,present,notpresent,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,normal,normal,notpresent,notpresent,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,normal,normal,notpresent,notpresent,47,6700,4.9,no,no,no,good,no,no,notckd
396,normal,normal,notpresent,notpresent,54,7800,6.2,no,no,no,good,no,no,notckd
397,normal,normal,notpresent,notpresent,49,6600,5.4,no,no,no,good,no,no,notckd
398,normal,normal,notpresent,notpresent,51,7200,5.9,no,no,no,good,no,no,notckd
399,normal,normal,notpresent,notpresent,53,6800,6.1,no,no,no,good,no,no,notckd

In [18]:
Qual_dataset.isnull().sum()

rbc               0
pc                0
pcc               0
ba                0
pcv               0
wc                0
rc                0
htn               0
dm                0
cad               0
appet             0
pe                0
ane               0
classification    0
dtype: int64

# Combine Quan_dataset, Qual_dataset DataFrames together using pd.concat

In [26]:
Preprocessed_dataset = pd.concat([Quan_dataset, Qual_dataset], axis=1)
Preprocessed_dataset

,id,age,bp,sg,al,su,bgr,bu,sc,sod,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0.0,48.0,80.0,1.020,1.0,0.0,121.0,36.0,1.2,138.0,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1.0,7.0,50.0,1.020,4.0,0.0,121.0,18.0,0.8,138.0,...,38,6000,Unknown,no,no,no,good,no,no,ckd
2,2.0,62.0,80.0,1.010,2.0,3.0,423.0,53.0,1.8,138.0,...,31,7500,Unknown,no,yes,no,poor,no,yes,ckd
3,3.0,48.0,70.0,1.005,4.0,0.0,117.0,56.0,3.8,111.0,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4.0,51.0,80.0,1.010,2.0,0.0,106.0,26.0,1.4,138.0,...,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395.0,55.0,80.0,1.020,0.0,0.0,140.0,49.0,0.5,150.0,...,47,6700,4.9,no,no,no,good,no,no,notckd
396,396.0,42.0,70.0,1.025,0.0,0.0,75.0,31.0,1.2,141.0,...,54,7800,6.2,no,no,no,good,no,no,notckd
397,397.0,12.0,80.0,1.020,0.0,0.0,100.0,26.0,0.6,137.0,...,49,6600,5.4,no,no,no,good,no,no,notckd
398,398.0,17.0,60.0,1.025,0.0,0.0,114.0,50.0,1.0,135.0,...,51,7200,5.9,no,no,no,good,no,no,notckd
399,399.0,58.0,80.0,1.025,0.0,0.0,131.0,18.0,1.1,141.0,...,53,6800,6.1,no,no,no,good,no,no,notckd

In [27]:
Preprocessed_dataset.isnull().sum()

id                0
age               0
bp                0
sg                0
al                0
su                0
bgr               0
bu                0
sc                0
sod               0
pot               0
hemo              0
rbc               0
pc                0
pcc               0
ba                0
pcv               0
wc                0
rc                0
htn               0
dm                0
cad               0
appet             0
pe                0
ane               0
classification    0
dtype: int64

# Save the Preprocessed dataset in csv file

In [29]:
Preprocessed_dataset.to_csv("Preprocessed_CKD.csv", index=False)